version: '3.8'

services:
  # Main application
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
      - ./logs:/app/logs
      - ./user_profiles:/app/user_profiles
      - ./shared:/app/shared
      - ./feedback:/app/feedback
      - ./memory:/app/memory
      - ./.env:/app/.env
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      - redis
      - mock-api
    restart: unless-stopped
    networks:
      - multi-modal-net

  # Redis for caching
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - multi-modal-net

  # Mock API server for development
  mock-api:
    build: 
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=development
    restart: unless-stopped
    networks:
      - multi-modal-net

  # MCP server for agent tools
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8001:8001"
    volumes:
      - ./outputs:/app/outputs
    environment:
      - FASTAPI_ENV=production
    restart: unless-stopped
    networks:
      - multi-modal-net

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - multi-modal-net
    profiles:
      - production

  # Monitoring with Grafana (optional)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - multi-modal-net
    profiles:
      - monitoring

volumes:
  redis_data:
  grafana_data:

networks:
  multi-modal-net:
    driver: bridge
