from __future__ import annotations

from pathlib import Path
from typing import Dict


def update_env(base_dir: Path, kv: Dict[str, str | None]) -> Path:
    """Create or update .env with provided key-values (preserve others)."""
    env_path = base_dir / ".env"
    existing: Dict[str, str] = {}

    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            existing[k.strip()] = v

    for k, v in kv.items():
        if v is None:
            continue
        existing[k] = str(v)

    content = "# Auto-generated by onboarding wizard\n" + "\n".join(f"{k}={v}" for k, v in existing.items()) + "\n"
    env_path.write_text(content, encoding="utf-8")
    return env_path 